language: python
python:
    - "3.8"
    - "3.7"
    - "3.6"
before_install:
    - pip install --upgrade pip
install:
    - make build
    - pip install codecov
script:
    - make test
    - coverage run -m unittest tests/*.py
after_success:
    - codecov
